### ISSUE TITLE
Visual Statistic on Daphile

### ISSUE THREAD

**Issue by wiesieks1** [AF-1/lms-visualstatistics#11]
I have trouble displaying statistics from Daphile
If Daphile's appearance in the browser is set to Default, the descriptions are not visible on the stats page, the appearance must be set to light, only then the subtitles are displayed and you can select options.
I showed it in the screenshot
![light](https://user-images.githubusercontent.com/86792004/219424652-459d8973-0100-4f93-bf38-88bbb0853e53.png)

![default](https://user-images.githubusercontent.com/86792004/219424787-c6381ca4-4560-4a10-aa94-0fe726ca9402.png)

**Comment by AF-1** [comment]
Visual Statistic's _light_ theme (used for all web skins except Material and Dark Default) has a _dark_ font color on a _light_ background (as shown in your first screenshot). I have never used Daphile but I suspect that it **enforces** a _light_ font color as part of its (darkish) UI which is, of course, not readable on a _light_ background. So it appears as if nothing is displayed but in fact the text should be there (screenshot 2).
If an app or a wrapper override Visual Statistics's color scheme, there's nothing I can do about this on my end. If you need this fixed, I think your best bet would be to ask the developer of Daphile to have a look.

That being said, I assume that you could use Visual Statistics with Daphile if you don't use the Daphile web UI:
- either use the LMS Default skin:  http://IPaddress:9000/plugins/VisualStatistics/html/list.html
- or install Material Skin, enable “Extras“ in Material's _Interface_ settings (because VS is listed in Extras, not Apps) and use: http://IPaddress:9000/material/

Just make sure to include port 9000 in your url. It might not work otherwise.

**Comment by wiesieks1** [comment]
thank you - this one works:


   - either use the LMS Default skin:
   http://IPaddress:9000/plugins/VisualStatistics/html/list.html
   <http://ipaddress:9000/plugins/VisualStatistics/html/list.html>


pt., 17 lut 2023 o 15:36 AF-1 ***@***.***> napisał(a):

**Comment by wiesieks1** [comment]
both work, with matirial skin too, thank you very much

pt., 17 lut 2023 o 16:17 Wiesław Sobczak ***@***.***>
napisał(a):
