### ISSUE TITLE
[REQUEST] Button to refresh text statistics

### ISSUE THREAD

**Issue by werdeil** [AF-1/lms-visualstatistics#12]
**Please read the *FAQ* (if available) and take a look at the *closed* issues first to avoid duplicates. Thank you.**

---

## DESCRIBE THE REQUEST
Not an issue but more a request: would it possible to add a button to refresh text statistics?

I used it a lot (it is one of the page alwyas open and I miss a button to refresh it (now I have to close the subview ans reopen it). As there is such button in all other subview I guess this is something possible.

<br><br>
## VERSION INFO
* LMS version: 8.4.0
* OS (version): Ubuntu 20.04
* Plugin version: 1.5.2
* Web skin/controller:   LMS Default

**Comment by AF-1** [comment]
Actually, only charts whose results can be changed by selecting a genre and/or decade have a refresh button. Other charts and the text statistics don't because VS was never intended for real-time updates. 

I don't know exactly what you need this for. It seems to be more of a power-user thing.

A refresh button for **charts** _without_ genre/decade selection doesn't make sense to me.
Anyway, I added an _Actualiser_ button below the library text stats, hidden by default.

Instead of a GUI pref setting you add `txtrefreshbtn: 1` to the _visualstatistics.prefs_ file to have the button displayed permanently. You'll probably have to delete your browser cache and restart LMS the first time. I hope this compromise suits your needs.

Not releasing 1.5.3 yet. Please let me know before if 1.5.3 is working for you or if you want different FR translations.

**Comment by werdeil** [comment]
Indeed this request is more a power-user thing. 

To explain more my need: I have the text statistics page always opened on a tab of my browser. I like to have a look at how some of the data have evolve since the last time (% tracks played once, % tracks rated, %album played...). I can always close the view and reopen it but I thought a refresh would be easier.

Once I saw a refresh button on other graphs I thought it could be nice to have it here too. Didn't see that it wasn't the case for graphe without selectors. I thought it was the same kind of usage as mine (having the graph always open and want to refresh it once in a while).

Do not release a version only for me, if you consider that this is not a necessary feature I'll live perfectly without it.

**Comment by AF-1** [comment]
I don't think I would ever add a refresh button to **charts** _without_ genre/decade selection.
But for the library **text** stats: a refresh button may not be a necessary feature but it doesn't do any harm either if it's hidden by default. Power users can enable it by adding `txtrefreshbtn: 1` to the _visualstatistics.prefs_ file. Other users will never notice it or be confused by it.
So maybe you can test 1.5.3 from this GitHub repo and see if everything is ok (button, translation). Then I can still release it this weekend.

**Comment by AF-1** [comment]
@werdeil I made some changes because there was still a problem with the (delimited) track count displayed after the virtual library names in the dropdown menu next  the info button. 

AFAIRC you used to have problems with that too (displaying 80 instead of 80,543 tracks).
Perhaps you can take a quick look at the latest commit and confirm that it is not causing any problems in this regard. Would appreciate that. Thanks.

P.S. You'll probably have to clear your browser cache.

**Comment by werdeil** [comment]
Sorry I didn't had the time to test the dropdown before you released the version 1.5.3. At least I don't have the issue on this version.

And the refresh button is there thanks a lot !
